"""Sweep non-photo content out of source folders.

Three categories of "stuff that doesn't belong in a slideshow folder",
each with its own flag and destination:

  --junk         OS metadata files (Thumbs.db, .DS_Store, desktop.ini,
                 .AppleDouble). Default action: DELETE + log. The only
                 deletion path in the tool — narrowly scoped to a
                 hardcoded JUNK_FILES allowlist. `--quarantine-junk`
                 flips back to move-to-mirrored-quarantine.

  --non-images   Arbitrary user files that aren't images (txt, pdf,
                 docx, zip, mp3, etc.). Always **moved** to
                 `<folder>-non-images/` — these are user content; the
                 "never delete" invariant applies.

  --videos       Video files (mov, mp4, m4v, avi, mkv, etc.). Always
                 **moved** to `<folder> - MOV/` (matches the existing
                 manual convention many users have for separating
                 videos from a photo slideshow). User content; never
                 deleted.

The flags can be combined. Each enabled category gets its own
destination folder and its own `sweep-manifest.json` so restores are
independent. A single `dedupe sweep <folder> --junk --non-images
--videos` invocation walks the source once and dispatches each file
to the right category.

Image files (extension in `IMAGE_EXTENSIONS`) are never touched by
sweep — that's what `scan` is for.

Live Photos pairing (a JPG + a paired MOV with the same basename) is
out of scope for v1: each file is processed independently. If
preserving the pairing matters, file an enhancement issue.
"""

from __future__ import annotations

import logging
import shutil
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path

from dedupe.manifest import AtomicManifestWriter
from dedupe.scan import IMAGE_EXTENSIONS
from dedupe.ui import UI
from dedupe.walk import WalkOptions, rel, walk_files

logger = logging.getLogger(__name__)


# --- category definitions ---------------------------------------------------

# Hardcoded allowlist of well-known auto-generated OS metadata filenames.
# Adding entries here is a deliberate exception to the project's "never
# delete files" invariant. Each entry should be:
#   1. Generated by the OS, not by the user.
#   2. Auto-regenerated when needed (so deletion is recoverable).
#   3. Universally recognized as "safe to delete" by mainstream tooling.
JUNK_FILES = frozenset(
    {
        "Thumbs.db",  # Windows Explorer thumbnail cache
        ".DS_Store",  # macOS Finder metadata
        "desktop.ini",  # Windows folder display config
        ".AppleDouble",  # macOS resource-fork sidecar (rare)
    }
)

# Video file extensions that `dedupe sweep --videos` will move out of
# a photo folder. Conservative-but-thorough: covers >99% of consumer
# video formats encountered in modern slideshow workflows. The action
# is "move to <folder> - MOV", not "delete", so the safety cost of an
# overzealous match is low; the cost of *missing* a video that breaks
# slideshow software is real.
#
# INCLUDED (20 extensions, grouped by source):
#
#   .mov  .mp4  .m4v   — Apple devices, modern phones, most cameras.
#                          .m4v is iTunes-era Apple variant of .mp4.
#   .avi                 — Older Windows-era captures, downloaded
#                          encodes.
#   .mkv                 — Matroska container; common for downloads
#                          and high-quality encodes.
#   .wmv  .asf           — Windows Media. Older Windows-recorded
#                          video and screen captures.
#   .flv  .f4v           — Flash video. Legacy web downloads from the
#                          pre-HTML5 era; still occasionally hosted.
#   .webm                — Open web video. WebRTC, screen recordings,
#                          some browsers' default save format.
#   .mpg  .mpeg          — MPEG-1/2 program streams. Old DVDs, older
#                          encodes.
#   .3gp  .3g2           — Mobile phone video. .3gp is GSM-era 3GPP;
#                          .3g2 is the CDMA equivalent (old Verizon).
#   .mts  .m2ts          — AVCHD camcorders (Sony, Panasonic). Common
#                          for anyone who used a consumer camcorder
#                          pre-2018.
#   .vob                 — DVD video. Anyone who ripped home-movie
#                          DVDs into a backup folder.
#   .ogv                 — Ogg video. Linux screencast tools default
#                          here.
#   .divx                — DivX-encoded AVI variants. Older but still
#                          encountered occasionally.
#   .lrv                 — GoPro low-resolution preview file. Always
#                          paired with the full-resolution .MP4;
#                          orphan .LRVs clutter folders.
#
# DELIBERATELY EXCLUDED:
#
#   .ts          — MPEG transport stream. Conflicts with TypeScript
#                  source code. The asymmetric cost of a false positive
#                  (moving a TS source file) outweighs the rare gain
#                  in a photo folder. If a user actually needs to
#                  sweep transport-stream video, file an enhancement.
#   .rm, .rmvb   — RealMedia. Effectively extinct.
#   .mxf         — Broadcast/professional. Niche; not seen in consumer
#                  slideshow workflows.
#   .hevc, .h264 — Raw codec streams without containers. Rare in
#                  consumer pipelines (containers wrap them).
#
# Adding entries: send a PR with a brief justification (what camera or
# software produces this format, and why slideshow workflows would
# encounter it). Lower bar than JUNK_FILES — videos are user content
# and the action is "move" not "delete" — but the same "we curate the
# list deliberately" principle applies.
VIDEO_EXTENSIONS = frozenset(
    {
        # Apple / modern phones / most cameras
        ".mov",
        ".mp4",
        ".m4v",
        # Older Windows / generic
        ".avi",
        ".mkv",
        ".wmv",
        ".asf",
        # Flash video (legacy web)
        ".flv",
        ".f4v",
        # Open web video
        ".webm",
        # MPEG program streams
        ".mpg",
        ".mpeg",
        # Mobile (3GPP / 3GPP2)
        ".3gp",
        ".3g2",
        # AVCHD camcorders (Sony / Panasonic)
        ".mts",
        ".m2ts",
        # DVD video
        ".vob",
        # Ogg video (Linux screencasts)
        ".ogv",
        # Older codec containers
        ".divx",
        # GoPro low-resolution preview file
        ".lrv",
    }
)


SWEEP_MANIFEST_NAME = "sweep-manifest.json"
SWEEP_MANIFEST_VERSION = 1

# Action constants stored in each manifest entry.
ACTION_DELETED = "deleted"
ACTION_MOVED = "moved"

# Category labels used internally for routing + manifest mode strings.
CATEGORY_JUNK = "junk"
CATEGORY_NON_IMAGES = "non-images"
CATEGORY_VIDEOS = "videos"


@dataclass(frozen=True)
class SweepOptions:
    source: Path

    # Junk-file category. The only category that can DELETE by default.
    sweep_junk: bool = False
    quarantine_junk: bool = False
    junk_folder: Path | None = None  # default: <source>-junk
    log_folder: Path | None = None  # default: <source>-sweep-log
    # ^ Used only when --junk is set without --quarantine-junk; stores
    # the deletion-only manifest. Ignored for the other categories
    # (their manifests sit alongside their quarantined files).

    # Non-image-files category. Always moves; never deletes.
    sweep_non_images: bool = False
    non_images_folder: Path | None = None  # default: <source>-non-images

    # Video-files category. Always moves; never deletes.
    sweep_videos: bool = False
    videos_folder: Path | None = None  # default: "<source> - MOV"

    dry_run: bool = False
    recursive: bool = True
    follow_symlinks: bool = False
    exclude_patterns: tuple[str, ...] = ()


@dataclass(frozen=True)
class SweepEntry:
    original_path: str
    action: str  # ACTION_DELETED or ACTION_MOVED
    new_path: str | None  # populated only when action == ACTION_MOVED
    size_bytes: int
    timestamp: str


@dataclass
class SweepResult:
    # Aggregate counters across all categories.
    files_scanned: int = 0  # files matching ANY enabled category
    files_swept: int = 0  # successfully deleted + moved
    bytes_swept: int = 0

    # Per-category counts (useful for the summary table).
    junk_swept: int = 0
    non_images_swept: int = 0
    videos_swept: int = 0

    errors: list[str] = field(default_factory=list)
    entries: list[SweepEntry] = field(default_factory=list)


# --- classification helpers -------------------------------------------------


def is_junk_file(path: Path) -> bool:
    """True if this filename is in the JUNK_FILES allowlist."""
    return path.name in JUNK_FILES


def is_video_file(path: Path) -> bool:
    """True if this file's extension is in VIDEO_EXTENSIONS."""
    return path.suffix.lower() in VIDEO_EXTENSIONS


def is_image_file(path: Path) -> bool:
    """True if this file's extension is in IMAGE_EXTENSIONS."""
    return path.suffix.lower() in IMAGE_EXTENSIONS


def _classify(path: Path) -> str | None:
    """Decide which sweep category a file belongs to (or None if it's an
    image / unknown). Junk takes precedence over video and non-images
    because some junk filenames could conceivably collide with weird
    extensions; we want the explicit allowlist to win.
    """
    if is_junk_file(path):
        return CATEGORY_JUNK
    if is_video_file(path):
        return CATEGORY_VIDEOS
    if is_image_file(path):
        return None  # images are never swept; that's scan's job
    return CATEGORY_NON_IMAGES


# --- manifest writers (per category, all backed by AtomicManifestWriter) ----


def _make_manifest_writer(
    path: Path,
    *,
    category: str,
    source_folder: Path,
    quarantine_folder: Path | None,
    mode: str,  # "delete" or "quarantine"
) -> AtomicManifestWriter[SweepEntry]:
    """Build an atomic writer for one category's sweep manifest."""
    header = {
        "version": SWEEP_MANIFEST_VERSION,
        "created_at": datetime.now(UTC).isoformat(),
        "source_folder": str(source_folder.resolve()),
        "quarantine_folder": (str(quarantine_folder.resolve()) if quarantine_folder else None),
        "category": category,
        "mode": mode,
    }
    return AtomicManifestWriter(path, header=header)


# --- per-category planning --------------------------------------------------


@dataclass(frozen=True)
class _CategoryPlan:
    """Per-category execution plan computed up front from SweepOptions.

    Centralizes "where do we put files / write the manifest / which
    action are we taking" so the main loop can stay simple.
    """

    label: str  # CATEGORY_*
    files: list[Path]
    destination: Path | None  # None for junk-delete (no destination folder)
    log_folder: Path  # where the manifest goes
    action: str  # ACTION_DELETED or ACTION_MOVED


def _default_destinations(opts: SweepOptions) -> dict[str, Path | None]:
    """Resolve the destination folder for each category, applying
    user-provided overrides where set and falling back to defaults.
    """
    src = opts.source
    return {
        CATEGORY_JUNK: (
            opts.junk_folder if opts.junk_folder is not None else src.parent / f"{src.name}-junk"
        )
        if opts.quarantine_junk
        else None,  # delete mode has no destination
        CATEGORY_NON_IMAGES: (
            opts.non_images_folder
            if opts.non_images_folder is not None
            else src.parent / f"{src.name}-non-images"
        ),
        CATEGORY_VIDEOS: (
            opts.videos_folder
            if opts.videos_folder is not None
            else src.parent / f"{src.name} - MOV"
        ),
    }


def _enabled_categories(opts: SweepOptions) -> set[str]:
    enabled = set()
    if opts.sweep_junk:
        enabled.add(CATEGORY_JUNK)
    if opts.sweep_non_images:
        enabled.add(CATEGORY_NON_IMAGES)
    if opts.sweep_videos:
        enabled.add(CATEGORY_VIDEOS)
    return enabled


# --- candidate-walk helper --------------------------------------------------


def _iter_candidate_files(opts: SweepOptions) -> list[Path]:
    """Walk the source tree and return every regular file (sorted).

    Calls `walk.walk_files` with `include_hidden=True` because junk
    files like `.DS_Store` are hidden by name. The classifier handles
    extension-level filtering downstream.
    """
    walk_opts = WalkOptions(
        source=opts.source,
        recursive=opts.recursive,
        follow_symlinks=opts.follow_symlinks,
        include_hidden=True,
        exclude_patterns=opts.exclude_patterns,
    )
    return sorted(walk_files(walk_opts))


# --- per-file execution -----------------------------------------------------


def _process_one(  # noqa: PLR0912 — linear failure-mode branches per action
    plan: _CategoryPlan,
    src_path: Path,
    *,
    source_root: Path,
    dry_run: bool,
    manifest: AtomicManifestWriter[SweepEntry] | None,
    ui: UI,
    result: SweepResult,
) -> None:
    """Apply a category's action to a single file. Records entry, advances
    counters, logs errors. Pure orchestration; no business logic here."""
    try:
        size = src_path.stat().st_size
    except OSError as exc:
        result.errors.append(f"stat failed for {src_path}: {exc}")
        ui.error(result.errors[-1])
        return

    if plan.action == ACTION_DELETED:
        verb = "would delete" if dry_run else "deleted"
        ui.info(
            f"  [dim]→[/dim] {verb} "
            f"[yellow]{rel(src_path, source_root)}[/yellow] ({size} bytes)"
        )
        if not dry_run:
            try:
                src_path.unlink()
            except OSError as exc:
                result.errors.append(f"delete failed for {src_path}: {exc}")
                ui.error(result.errors[-1])
                return
        entry = SweepEntry(
            original_path=str(src_path),
            action=ACTION_DELETED,
            new_path=None,
            size_bytes=size,
            timestamp=datetime.now(UTC).isoformat(),
        )
    else:  # ACTION_MOVED
        assert plan.destination is not None
        try:
            rel_path = src_path.resolve().relative_to(source_root.resolve())
        except ValueError as exc:
            result.errors.append(f"could not map path {src_path}: {exc}")
            ui.error(result.errors[-1])
            return
        dest = plan.destination / rel_path
        if dest.exists():
            result.errors.append(f"refusing to overwrite: {dest}")
            ui.error(result.errors[-1])
            return
        verb = "would move" if dry_run else "moved"
        ui.info(
            f"  [dim]→[/dim] {verb} "
            f"[yellow]{rel(src_path, source_root)}[/yellow] → "
            f"[green]{rel(dest, plan.destination)}[/green] "
            f"(in {plan.label})"
        )
        if not dry_run:
            try:
                dest.parent.mkdir(parents=True, exist_ok=True)
                shutil.move(str(src_path), str(dest))
            except OSError as exc:
                result.errors.append(f"move failed for {src_path} -> {dest}: {exc}")
                ui.error(result.errors[-1])
                return
        entry = SweepEntry(
            original_path=str(src_path),
            action=ACTION_MOVED,
            new_path=str(dest),
            size_bytes=size,
            timestamp=datetime.now(UTC).isoformat(),
        )

    if manifest is not None:
        manifest.add(entry)
    result.entries.append(entry)
    result.files_swept += 1
    result.bytes_swept += size
    if plan.label == CATEGORY_JUNK:
        result.junk_swept += 1
    elif plan.label == CATEGORY_NON_IMAGES:
        result.non_images_swept += 1
    elif plan.label == CATEGORY_VIDEOS:
        result.videos_swept += 1


# --- top-level orchestration ------------------------------------------------


def run_sweep(opts: SweepOptions, ui: UI) -> SweepResult:
    """Walk the source folder once and dispatch each file to its category.

    Each enabled category gets its own destination folder and manifest;
    deletes (junk only) write to a sibling sweep-log folder.
    """
    if not opts.source.exists():
        raise FileNotFoundError(f"source folder does not exist: {opts.source}")
    if not opts.source.is_dir():
        raise NotADirectoryError(f"source is not a directory: {opts.source}")

    enabled = _enabled_categories(opts)
    if not enabled:
        ui.warn(
            "no sweep mode requested. Pass --junk for OS metadata files, "
            "--non-images for arbitrary non-image content, or --videos for "
            "video files. Modes can be combined."
        )
        return SweepResult()

    # Phase 1: walk + classify into per-category buckets.
    all_files = _iter_candidate_files(opts)
    buckets: dict[str, list[Path]] = {
        CATEGORY_JUNK: [],
        CATEGORY_NON_IMAGES: [],
        CATEGORY_VIDEOS: [],
    }
    for path in all_files:
        category = _classify(path)
        if category is None or category not in enabled:
            continue
        buckets[category].append(path)

    total_eligible = sum(len(v) for v in buckets.values())
    ui.detail(
        f"walked {len(all_files)} file(s); "
        f"{total_eligible} match enabled sweep categories "
        f"(junk={len(buckets[CATEGORY_JUNK])}, "
        f"non-images={len(buckets[CATEGORY_NON_IMAGES])}, "
        f"videos={len(buckets[CATEGORY_VIDEOS])})"
    )

    result = SweepResult(files_scanned=total_eligible)
    if total_eligible == 0:
        ui.success("no sweep candidates found")
        return result

    # Phase 2: build per-category plans (destination, action, log folder).
    destinations = _default_destinations(opts)
    plans: list[_CategoryPlan] = []
    for category in (CATEGORY_JUNK, CATEGORY_NON_IMAGES, CATEGORY_VIDEOS):
        files = buckets[category]
        if not files:
            continue
        if category == CATEGORY_JUNK:
            destination = destinations[CATEGORY_JUNK]  # None when delete mode
            action = ACTION_MOVED if opts.quarantine_junk else ACTION_DELETED
            log_folder = (
                destination
                if destination is not None
                else (opts.log_folder or opts.source.parent / f"{opts.source.name}-sweep-log")
            )
        else:
            destination = destinations[category]
            assert destination is not None
            action = ACTION_MOVED
            log_folder = destination
        plans.append(
            _CategoryPlan(
                label=category,
                files=files,
                destination=destination,
                log_folder=log_folder,
                action=action,
            )
        )

    # Phase 3: process each category. Each gets its own manifest.
    for plan in plans:
        _run_category(plan, opts, ui, result)

    return result


def _run_category(
    plan: _CategoryPlan,
    opts: SweepOptions,
    ui: UI,
    result: SweepResult,
) -> None:
    """Run one category's portion of the sweep."""
    mode_label = "quarantine" if plan.action == ACTION_MOVED else "delete"

    if plan.action == ACTION_DELETED:
        ui.info(
            f"[bold]{plan.label}[/bold]: deleting "
            f"{len(plan.files)} file(s); audit log: {plan.log_folder}"
        )
    else:
        ui.info(
            f"[bold]{plan.label}[/bold]: moving " f"{len(plan.files)} file(s) → {plan.destination}"
        )

    manifest_writer: AtomicManifestWriter[SweepEntry] | None = None
    if not opts.dry_run:
        plan.log_folder.mkdir(parents=True, exist_ok=True)
        manifest_writer = _make_manifest_writer(
            path=plan.log_folder / SWEEP_MANIFEST_NAME,
            category=plan.label,
            source_folder=opts.source,
            quarantine_folder=plan.destination,
            mode=mode_label,
        )

    for src_path in plan.files:
        _process_one(
            plan,
            src_path,
            source_root=opts.source,
            dry_run=opts.dry_run,
            manifest=manifest_writer,
            ui=ui,
            result=result,
        )
