"""Sweep junk files (and, in the future, other non-photo content) out of source folders.

Today's scope: a `--junk` mode that handles auto-generated OS metadata
files — `Thumbs.db`, `.DS_Store`, and friends. By default these files
are **deleted** (with a manifest log). They are auto-regenerated by their
respective OSes whenever a user re-views the folder, so the deletion is
recoverable in a sense the project's "never delete" rule doesn't usually
need to permit.

The `--quarantine-junk` flag flips the default to the safer "move to
sibling folder, mirroring layout" pattern — same shape as `scan`'s dups
folder.

Future: `--non-images` (#31) and `--videos` (#32) modes for arbitrary
user content. Those WILL move-to-quarantine by default; only the small
hardcoded `JUNK_FILES` allowlist gets the delete-by-default treatment.
"""

from __future__ import annotations

import logging
import shutil
from collections.abc import Iterator
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path

from dedupe.manifest import AtomicManifestWriter
from dedupe.ui import UI
from dedupe.walk import WalkOptions, rel, walk_files

logger = logging.getLogger(__name__)


# Hardcoded allowlist of well-known auto-generated OS metadata filenames.
# Adding entries to this set is a deliberate exception to the project's
# "never delete files" invariant. Each entry should be:
#   1. Generated by the OS, not by the user.
#   2. Auto-regenerated when needed (so deletion is recoverable).
#   3. Universally recognized as "safe to delete" by mainstream tooling.
JUNK_FILES = frozenset(
    {
        "Thumbs.db",  # Windows Explorer thumbnail cache
        ".DS_Store",  # macOS Finder metadata
        "desktop.ini",  # Windows folder display config
        ".AppleDouble",  # macOS resource-fork sidecar (rare)
    }
)

SWEEP_MANIFEST_NAME = "sweep-manifest.json"
SWEEP_MANIFEST_VERSION = 1

# Action constants stored in each manifest entry.
ACTION_DELETED = "deleted"
ACTION_MOVED = "moved"


@dataclass(frozen=True)
class SweepOptions:
    source: Path
    sweep_junk: bool = False
    quarantine_junk: bool = False
    junk_folder: Path | None = None  # default: <source>-junk
    log_folder: Path | None = None  # default: <source>-sweep-log
    dry_run: bool = False
    recursive: bool = True
    follow_symlinks: bool = False
    exclude_patterns: tuple[str, ...] = ()


@dataclass(frozen=True)
class SweepEntry:
    original_path: str
    action: str  # ACTION_DELETED or ACTION_MOVED
    new_path: str | None  # populated only when action == ACTION_MOVED
    size_bytes: int
    timestamp: str


@dataclass
class SweepResult:
    files_scanned: int = 0
    files_swept: int = 0  # deleted + moved
    bytes_swept: int = 0
    errors: list[str] = field(default_factory=list)
    entries: list[SweepEntry] = field(default_factory=list)


def _make_sweep_manifest_writer(
    path: Path,
    *,
    source_folder: Path,
    quarantine_folder: Path | None,
    mode: str,  # "delete" or "quarantine"
) -> AtomicManifestWriter[SweepEntry]:
    """Build an atomic writer for the sweep manifest."""
    header = {
        "version": SWEEP_MANIFEST_VERSION,
        "created_at": datetime.now(UTC).isoformat(),
        "source_folder": str(source_folder.resolve()),
        "quarantine_folder": (str(quarantine_folder.resolve()) if quarantine_folder else None),
        "mode": mode,
    }
    return AtomicManifestWriter(path, header=header)


def is_junk_file(path: Path) -> bool:
    """True if this filename is in the JUNK_FILES allowlist."""
    return path.name in JUNK_FILES


def _iter_candidate_files(opts: SweepOptions) -> Iterator[Path]:
    """Walk the source tree and yield every regular file matching opts.

    Calls `walk.walk_files` with `include_hidden=True` because junk files
    like `.DS_Store` are hidden by name — the default hidden-file filter
    would skip exactly what we're trying to find. No predicate; the
    `--junk` mode narrows by `JUNK_FILES` afterwards.
    """
    walk_opts = WalkOptions(
        source=opts.source,
        recursive=opts.recursive,
        follow_symlinks=opts.follow_symlinks,
        include_hidden=True,
        exclude_patterns=opts.exclude_patterns,
    )
    yield from walk_files(walk_opts)


def _quarantine_destination(original: Path, source: Path, quarantine_folder: Path) -> Path:
    """source/foo/Thumbs.db -> quarantine/foo/Thumbs.db (mirrored layout)."""
    rel_path = original.resolve().relative_to(source.resolve())
    return quarantine_folder / rel_path


def run_sweep(opts: SweepOptions, ui: UI) -> SweepResult:  # noqa: PLR0912, PLR0915 — orchestrator with linear failure-mode branches
    """Walk the source tree and sweep matching files.

    Today only `--junk` is implemented. Without that flag, the walk
    finds nothing eligible and the result is a no-op.
    """
    if not opts.source.exists():
        raise FileNotFoundError(f"source folder does not exist: {opts.source}")
    if not opts.source.is_dir():
        raise NotADirectoryError(f"source is not a directory: {opts.source}")

    if not opts.sweep_junk:
        # No mode flags set. Bail with a clear message.
        ui.warn(
            "no sweep mode requested. Pass --junk to sweep auto-generated "
            "OS metadata files (Thumbs.db, .DS_Store, etc.). Future modes: "
            "--non-images (#31), --videos (#32)."
        )
        return SweepResult()

    # Identify candidate files (junk only, in this initial cut).
    all_files = sorted(_iter_candidate_files(opts))
    junk_files = [p for p in all_files if is_junk_file(p)]
    ui.detail(
        f"walked {len(all_files)} file(s), {len(junk_files)} match the " f"junk-file allowlist"
    )

    result = SweepResult(files_scanned=len(junk_files))
    if not junk_files:
        ui.success("no junk files found")
        return result

    # Decide mode: delete (default) or quarantine.
    quarantine_folder: Path | None = None
    log_folder: Path
    mode_label: str

    if opts.quarantine_junk:
        quarantine_folder = opts.junk_folder or opts.source.parent / f"{opts.source.name}-junk"
        log_folder = quarantine_folder  # manifest lives alongside the quarantined files
        mode_label = "quarantine"
        ui.info(
            f"Sweeping [bold]{len(junk_files)}[/bold] junk file(s) to "
            f"[bold]{quarantine_folder}[/bold]"
        )
    else:
        log_folder = opts.log_folder or opts.source.parent / f"{opts.source.name}-sweep-log"
        mode_label = "delete"
        ui.info(
            f"Sweeping (deleting) [bold]{len(junk_files)}[/bold] junk file(s); "
            f"audit log: [bold]{log_folder}[/bold]"
        )
        ui.info(
            "[dim](junk files are auto-regenerated by their OS — pass "
            "--quarantine-junk to move instead of delete)[/dim]"
        )

    # Set up manifest writer (skip in dry-run; just collect entries).
    manifest_writer: AtomicManifestWriter[SweepEntry] | None = None
    if not opts.dry_run:
        log_folder.mkdir(parents=True, exist_ok=True)
        manifest_writer = _make_sweep_manifest_writer(
            path=log_folder / SWEEP_MANIFEST_NAME,
            source_folder=opts.source,
            quarantine_folder=quarantine_folder,
            mode=mode_label,
        )

    for path in junk_files:
        try:
            size = path.stat().st_size
        except OSError as exc:
            result.errors.append(f"stat failed for {path}: {exc}")
            ui.error(result.errors[-1])
            continue

        if opts.quarantine_junk:
            assert quarantine_folder is not None  # guaranteed by branch above
            try:
                dest = _quarantine_destination(path, opts.source, quarantine_folder)
            except ValueError as exc:
                result.errors.append(f"could not map path {path}: {exc}")
                ui.error(result.errors[-1])
                continue
            if dest.exists():
                result.errors.append(f"refusing to overwrite: {dest}")
                ui.error(result.errors[-1])
                continue
            verb = "would move" if opts.dry_run else "moved"
            ui.info(
                f"  [dim]→[/dim] {verb} "
                f"[yellow]{rel(path, opts.source)}[/yellow] → "
                f"[green]{rel(dest, quarantine_folder)}[/green] (in junk)"
            )
            if not opts.dry_run:
                try:
                    dest.parent.mkdir(parents=True, exist_ok=True)
                    shutil.move(str(path), str(dest))
                except OSError as exc:
                    result.errors.append(f"move failed for {path} -> {dest}: {exc}")
                    ui.error(result.errors[-1])
                    continue
            entry = SweepEntry(
                original_path=str(path),
                action=ACTION_MOVED,
                new_path=str(dest),
                size_bytes=size,
                timestamp=datetime.now(UTC).isoformat(),
            )
        else:
            verb = "would delete" if opts.dry_run else "deleted"
            ui.info(
                f"  [dim]→[/dim] {verb} "
                f"[yellow]{rel(path, opts.source)}[/yellow] "
                f"({size} bytes)"
            )
            if not opts.dry_run:
                try:
                    path.unlink()
                except OSError as exc:
                    result.errors.append(f"delete failed for {path}: {exc}")
                    ui.error(result.errors[-1])
                    continue
            entry = SweepEntry(
                original_path=str(path),
                action=ACTION_DELETED,
                new_path=None,
                size_bytes=size,
                timestamp=datetime.now(UTC).isoformat(),
            )

        result.files_swept += 1
        result.bytes_swept += size
        result.entries.append(entry)
        if manifest_writer is not None:
            manifest_writer.add(entry)

    return result
