"""`dedupe sweep` subcommand: parser config + handler."""

from __future__ import annotations

import argparse
from pathlib import Path

from dedupe.cli.output import format_bytes
from dedupe.cli.parser import (
    EXIT_ERROR,
    EXIT_OK,
    EXIT_PARTIAL,
    add_global_flags,
    flatten_list_arg,
)
from dedupe.ui import UI


def register(sub: argparse._SubParsersAction) -> None:
    p = sub.add_parser(
        "sweep",
        help="Move/delete non-photo content (junk files, etc.) out of source folders",
        description=(
            "Walk a folder for non-photo content and clean it out. "
            "Today: --junk mode for auto-generated OS metadata files "
            "(Thumbs.db, .DS_Store, desktop.ini, .AppleDouble). Default "
            "action for junk files is DELETE (with manifest log) since "
            "they're auto-regenerated by their OS. Pass "
            "--quarantine-junk to move them to a sibling folder instead."
        ),
    )
    add_global_flags(p)
    p.add_argument("folder", type=Path, help="Folder to sweep")
    p.add_argument(
        "--junk",
        dest="sweep_junk",
        action="store_true",
        help=(
            "Sweep auto-generated OS metadata files (Thumbs.db, .DS_Store, "
            "desktop.ini, .AppleDouble). Default action: delete + log."
        ),
    )
    p.add_argument(
        "--quarantine-junk",
        action="store_true",
        help=(
            "Instead of deleting, MOVE junk files to a sibling folder "
            "(default: <folder>-junk) mirroring layout. Safer but creates a "
            "tree of nested empty-ish dirs."
        ),
    )
    p.add_argument(
        "--junk-folder",
        type=Path,
        default=None,
        metavar="PATH",
        help=("Where to move junk files when --quarantine-junk is set " "(default: <folder>-junk)"),
    )
    p.add_argument(
        "--log-folder",
        type=Path,
        default=None,
        metavar="PATH",
        help=(
            "Where to write the sweep manifest in delete mode "
            "(default: <folder>-sweep-log). Ignored with --quarantine-junk "
            "(manifest goes alongside the quarantined files)."
        ),
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Report what would be deleted/moved without changing anything",
    )
    recurse = p.add_mutually_exclusive_group()
    recurse.add_argument(
        "--recursive",
        "-r",
        dest="recursive",
        action="store_true",
        default=True,
        help="Recurse into subdirectories (default)",
    )
    recurse.add_argument(
        "--no-recursive",
        dest="recursive",
        action="store_false",
        help="Do not recurse into subdirectories",
    )
    p.add_argument(
        "--follow-symlinks",
        action="store_true",
        help="Follow symlinks (default: skip)",
    )
    p.add_argument(
        "--exclude",
        action="append",
        metavar="PATTERN",
        help=(
            "Glob pattern to exclude (repeatable; comma-separated lists "
            "also accepted). Matched against the path relative to <folder> "
            "AND the basename."
        ),
    )
    p.set_defaults(func=_cmd_sweep)


def _emit_summary(result, opts, ui: UI) -> None:
    """Print the rich-mode summary block. Extracted from `_cmd_sweep` to keep
    the handler's branch count low."""
    verb = "would sweep" if opts.dry_run else ("moved" if opts.quarantine_junk else "deleted")
    ui.info("")
    ui.info("[bold]Summary[/bold]")
    ui.info(f"  files matched:  {result.files_scanned}")
    ui.info(f"  files {verb}: {result.files_swept}")
    ui.info(f"  bytes swept:    {result.bytes_swept} ({format_bytes(result.bytes_swept)})")
    if result.files_swept and not opts.dry_run:
        if opts.quarantine_junk:
            target = opts.junk_folder or (opts.source.parent / f"{opts.source.name}-junk")
            ui.success(f"  quarantine: {target}")
        else:
            target = opts.log_folder or (opts.source.parent / f"{opts.source.name}-sweep-log")
            ui.success(f"  audit log:  {target}/sweep-manifest.json")
    if result.errors:
        ui.warn(f"completed with {len(result.errors)} error(s)")


def _cmd_sweep(args: argparse.Namespace, ui: UI) -> int:
    from dedupe.sweep import SweepOptions, run_sweep  # noqa: PLC0415

    opts = SweepOptions(
        source=args.folder,
        sweep_junk=args.sweep_junk,
        quarantine_junk=args.quarantine_junk,
        junk_folder=args.junk_folder,
        log_folder=args.log_folder,
        dry_run=args.dry_run,
        recursive=args.recursive,
        follow_symlinks=args.follow_symlinks,
        exclude_patterns=tuple(flatten_list_arg(args.exclude)),
    )

    try:
        result = run_sweep(opts, ui)
    except (FileNotFoundError, NotADirectoryError) as exc:
        ui.error(str(exc))
        return EXIT_ERROR

    if ui.config.json_mode:
        mode = "quarantine" if opts.quarantine_junk else "delete"
        ui.emit_json(
            {
                "command": "sweep",
                "dry_run": opts.dry_run,
                "source": str(opts.source),
                "mode": mode,
                "sweep_junk": opts.sweep_junk,
                "junk_folder": str(opts.junk_folder) if opts.junk_folder else None,
                "log_folder": str(opts.log_folder) if opts.log_folder else None,
                "files_scanned": result.files_scanned,
                "files_swept": result.files_swept,
                "bytes_swept": result.bytes_swept,
                "errors": result.errors,
                "entries": [e.__dict__ for e in result.entries],
            }
        )
    else:
        _emit_summary(result, opts, ui)

    return EXIT_PARTIAL if result.errors else EXIT_OK
